# Generated by Django 3.1.13 on 2021-07-23 20:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('android_package_name', models.CharField(blank=True, help_text='com.company.appname', max_length=255)),
                ('apple_app_id', models.CharField(blank=True, help_text='id1234567890', max_length=36)),
            ],
            options={
                'ordering': ['android_package_name', 'apple_app_id'],
            },
        ),
    ]
