# Generated by Django 3.2.5 on 2021-07-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_deep_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['android_package_name', 'ios_bundle_id']},
        ),
        migrations.RemoveField(
            model_name='app',
            name='apple_app_id',
        ),
        migrations.AddField(
            model_name='app',
            name='android_app',
            field=models.BooleanField(default=False, verbose_name='I have an Android App'),
        ),
        migrations.AddField(
            model_name='app',
            name='android_custom_url',
            field=models.URLField(blank=True, help_text='A URL to fallback to when the app is not installed.', verbose_name='Custom URL'),
        ),
        migrations.AddField(
            model_name='app',
            name='android_uri_scheme',
            field=models.CharField(blank=True, help_text='myapp://', max_length=255, verbose_name='Android URI Scheme'),
        ),
        migrations.AddField(
            model_name='app',
            name='android_url',
            field=models.URLField(blank=True, help_text='If blank, users will be redirected to the Default URL.', verbose_name='Android URL'),
        ),
        migrations.AddField(
            model_name='app',
            name='default_url',
            field=models.URLField(blank=True, help_text='Your fallback URL for mobile devices that do not have a specified redirect.', verbose_name='Default URL'),
        ),
        migrations.AddField(
            model_name='app',
            name='ios_app',
            field=models.BooleanField(default=False, verbose_name='I have an iOS App'),
        ),
        migrations.AddField(
            model_name='app',
            name='ios_bundle_id',
            field=models.CharField(blank=True, help_text='id1234567890', max_length=36, verbose_name='iOS Bundle ID'),
        ),
        migrations.AddField(
            model_name='app',
            name='ios_custom_url',
            field=models.URLField(blank=True, help_text='A URL to fallback to when the app is not installed.', verbose_name='Custom URL'),
        ),
        migrations.AddField(
            model_name='app',
            name='ios_url',
            field=models.URLField(blank=True, help_text='If blank, users will be redirected to the Default URL.', verbose_name='iOS URL'),
        ),
        migrations.AlterField(
            model_name='app',
            name='android_package_name',
            field=models.CharField(blank=True, help_text='(e.g. - com.company.appname) If blank, users will be redirected to the Default URL', max_length=255, verbose_name='Android Package Name'),
        ),
    ]
