# Generated by Django 3.1.13 on 2021-07-23 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_deep_link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ip_data', models.JSONField(blank=True, default=dict, help_text='Must be valid JSON', null=True)),
                ('ua_data', models.JSONField(blank=True, default=dict, help_text='Must be valid JSON', null=True)),
                ('deep_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='django_deep_link.appstore')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
