# Generated by Django 3.2.5 on 2021-07-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_deep_link', '0002_auto_20210727_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ios_uri_scheme',
            field=models.CharField(blank=True, help_text='myapp://', max_length=255, verbose_name='iOS URI Scheme'),
        ),
    ]
