# Generated by Django 3.1.13 on 2021-07-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_deep_link', '0002_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstore',
            name='name',
            field=models.CharField(default='Default', help_text='The application display name.', max_length=255),
            preserve_default=False,
        ),
    ]
