# Generated by Django 3.2.5 on 2021-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_deep_link', '0005_auto_20210729_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='query_data',
            field=models.JSONField(blank=True, default=dict, help_text='Must be valid JSON', verbose_name='Query data'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip_data',
            field=models.JSONField(blank=True, default=dict, help_text='Must be valid JSON', verbose_name='IP geodata'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ua_data',
            field=models.JSONField(blank=True, default=dict, help_text='Must be valid JSON', verbose_name='User agent data'),
        ),
    ]
