# Generated by Django 4.2.9 on 2024-04-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_deep_link",
            "0002_alter_visit_ip_address_alter_visit_ip_data_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="ip_address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="IP Address"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="ip_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Must be valid JSON",
                verbose_name="IP Data",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="ua_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Must be valid JSON",
                verbose_name="User Agent Data",
            ),
        ),
    ]
